### ISSUE TITLE
Improve logic for version bumping in CD

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-quack-quack-mvp#196]
Currently, all cases are hard-coded, so maintenance is not easy.

```yml
# 🤯
# https://github.com/duckie-team/duckie-quack-quack/blob/develop/.github/workflows/artifact-publish.yml

 - name: Bump artifact version (type_Major, target_LintQuack)
   if: ${{
     contains(github.event.pull_request.labels.*.name, 'bump_major') &&
     contains(github.event.pull_request.labels.*.name, 'target_lint-quack')
     }}
   run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="LintQuack"

 - name: Bump artifact version (type_Major, target_LintCompose)
   if: ${{
     contains(github.event.pull_request.labels.*.name, 'bump_major') &&
     contains(github.event.pull_request.labels.*.name, 'target_lint-compose')
     }}
   run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="LintCompose"

 - name: Bump artifact version (type_Major, target_UiComponents)
   if: ${{
     contains(github.event.pull_request.labels.*.name, 'bump_major') &&
     contains(github.event.pull_request.labels.*.name, 'target_ui-components')
     }}
   run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="UiComponents"

 - name: Bump artifact version (type_Minor, target_LintCore)
   if: ${{
     contains(github.event.pull_request.labels.*.name, 'bump_minor') &&
     contains(github.event.pull_request.labels.*.name, 'target_lint-core')
     }}
   run: ./gradlew bumpVersion --scan -Ptype="Minor" -Ptarget="LintCore"

# ...
```

We need to find a way to implement it by eliminating the repetitive structure.

--

## Reference

[conference-app-2022/CommentPR.yml](https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/CommentPR.yml#L19) 를 보면 자바스크립트를 사용하고 있다.

![image](https://user-images.githubusercontent.com/40740128/194375540-5f35e48e-5776-4fa7-a170-c02f49fb80b1.png)

나도 이런식으로 해결할 수 있지 않을까?
